### ISSUE TITLE
Where to adjust keybinds? 

### ISSUE THREAD

**Issue by Bhawkins94** [PapyElGringo/material-awesome#10]
Not really an issue, I might have just missed it. Could use some help to find where keybinds can be added and change what opens what.

**Comment by Elv13** [comment]
/me sneak in

Here for the global ones:

https://github.com/PapyElGringo/material-awesome/tree/master/conf/keys

Here for the window specific ones:

https://github.com/PapyElGringo/material-awesome/blob/master/conf/client/keys.lua

Awesome doc along with some examples: 

https://awesomewm.org/apidoc/documentation/05-awesomerc.md.html#Key_bindings

**Comment by PapyElGringo** [comment]
Yeah thanks Elv :)

You can also check the tags file
https://github.com/PapyElGringo/material-awesome/blob/master/conf/tags.lua

To set the default apps for each tags ( to configure the + buttons on the
top bar)

**Comment by PapyElGringo** [comment]
I'll do some documentation and improvements about the configuration soon

**Comment by PapyElGringo** [comment]
Can I close this?

**Comment by Bhawkins94** [comment]
Yes, found where to play around with some settings
