### ISSUE TITLE
lock widget

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#14]
lock widget also not working. leaving my laptop without lock. :( lets pray no one use it. :)

**Comment by PapyElGringo** [comment]
The lock system currenlty depend on i3lock-fancy-rapid :)

**Comment by najamsk** [comment]
is this package name? that i have to install ? i am on arch (manjaro)

**Comment by PapyElGringo** [comment]
You got it on AUR at i3lock-fancy-rapid-git

**Comment by najamsk** [comment]
bro i like how u respond so fast? i mean seriously u are into this stuff. #respect

**Comment by PapyElGringo** [comment]
Thanks man ! Don't hesitate to close your issues when you feel it's answered or fixed :)

**Comment by najamsk** [comment]
sure i will currently at work. will play with few ideas and will be closing accordingly

**Comment by najamsk** [comment]
plus please make youtube video on awesome wm and ur workflow. i am using i3gaps and really like to know what awesome offers more then i3gaps and how to be more productive (with mouse and keyboard and with keyboard only)

**Comment by najamsk** [comment]
i3lock-fancy-rapid-git installed this but still locking is not working.

**Comment by PapyElGringo** [comment]
How do you lock? I pushed some fixes to uniformise the lock system if you want to pull

**Comment by najamsk** [comment]
i open side panel which i believe is rofi. i use mouse to open it wish i know the keybind to open that sidepanel with rofi ui shown.

anyhow from sidepanel i click on end work session. then from next ui clicking lock icon and nothing happening.

**Comment by najamsk** [comment]
i do use 4.2 branch of your setup. since running awesome 4.2 on manjaro

**Comment by najamsk** [comment]
i have downloaded your changes in my folder there were 3 files that are changed. i copied them to my config folder restarted aweseome wm and tried to lock again but still nothing get locked.

**Comment by PapyElGringo** [comment]
try to type `i3lock-fancy-rapid 5 3 -k --timecolor=ffffffff --datecolor=ffffffff` in shell

**Comment by najamsk** [comment]
λ najam [~] → i3lock-fancy-rapid 5 3 -k --timecolor=ffffffff --datecolor=ffffffff
i3lock: invalid option -- 'k'

**Comment by PapyElGringo** [comment]
Try to remove i3lock and install i3lock-rapid

**Comment by najamsk** [comment]
i3lock-fancy-rapid 5 3

this works and blur the whole window and locked it.

**Comment by najamsk** [comment]
lock = 'i3lock-fancy-rapid 5 3'
changing code to above in apps.lua seems to work
