### ISSUE TITLE
window management options

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#16]
on top right i see two tiling modes. max and tile. can we have floating or other options there. with keybind to switch mode for each tag.?

**Comment by PapyElGringo** [comment]
Yeah we could but I want to keep the config the most simple possible and I want it to be very predictible.
The goal of the config here is to avoid the floating mode. That's how I could remove the titles bars without problems. 

So it's possible I could add some others options but not the floating mode and for now the only 2 modes I feel usefull is the tileling for multitasking and maximized for focus work.

If you find some other mode usefull don't hesitate to explain me why :)

**Comment by najamsk** [comment]
i dont know using i3gaps i was able to switch modes and make a window floating to resize it or shift to somewhere else. if i get stuck somewhere maybe note down things and will let you know. instead of floating maybe vertical tile like i3 or changing tile orientation on fly makes sense? like where next window will appear horizontal or vertical. i am so new to awesome if what i am asking contradicts to awesome wm way of doing then please ignore.

**Comment by PapyElGringo** [comment]
Something need to be clarifyed. My configuration is not made with AwesomeWM but it's not the whole AwesomeWM. With AwesomeWM you can do almost everything you want like clone i3-gaps. 
I have my own vision of how I want my desktop environment to work but you could want something else and change the configuration to make it's work like that.
I locked up my config to only 2 layout: Maximized and Tileable but awesome can do much more https://awesomewm.org/doc/api/libraries/awful.layout.html#Client_layouts

**Comment by najamsk** [comment]
i got that idea. but to make changes to your configuration need to learn alot :) after all its maybe more then 4 months of configuration. thats why asking stupid questions.
