### ISSUE TITLE
launch rofi 

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#17]
on i3gaps and some other awesome configuration when i press super+D rofi shows up. is there anything like that in this config. when mouse is away i like to just reach rofi faster.

**Comment by PapyElGringo** [comment]
cmd+e for execute

**Comment by najamsk** [comment]
so which file i need to read ? to get these kind of bindings. where i can set my bindings. like to launch terminal, firefox, filemanger, filemanger with admin permission.

**Comment by PapyElGringo** [comment]
All the config are in the conf folders check them :)

**Comment by najamsk** [comment]
rofi launching perfectly
