### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#18]
from where u get icons for tags? like chrome and stuff. I use firefox so want to replace them but dont want  things to get out of hand or look different from each other.

**Comment by PapyElGringo** [comment]
1) Get an icon at https://materialdesignicons.com
2) put it in /theme/icons
3) Edit the icon and change width and height to 240
4) Add fill="#ffffff" to the tag <d>
5) Edit the file https://github.com/PapyElGringo/material-awesome/blob/master/theme/icons/init.lua accordingly

**Comment by najamsk** [comment]
done and thanks. :)
