### ISSUE TITLE
more workspaces or tags

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#19]
i like to have more workspaces. maybe 10 like i3gaps i get used to it. which file to modify? i have a feeling this one is the most stupidest question from all i have asked.

**Comment by PapyElGringo** [comment]
1) Pull the last commits
2) Edit https://github.com/PapyElGringo/material-awesome/blob/master/conf/tags.lua

**Comment by najamsk** [comment]
added more tags with icons.
