### ISSUE TITLE
Error calling a nil value

### ISSUE THREAD

**Issue by TheBeachMaster** [PapyElGringo/material-awesome#2]
Hello Papy,

After much fumbling, I attempted to install AwesomeWM (moving from Deepin) however, I got into a bit of trouble here.

This particular line  results into an error: `attempt to call nil value (field 'single-instance')` . 

**Distro : Arch Linux x86_64**
**Kernel v4.20.6**

https://github.com/PapyElGringo/material-awesome/blob/a1523016c2f75eaaf197b510158ee980eba9619e/module/auto-start.lua#L4

**Comment by PapyElGringo** [comment]
You probably have awesomewm 4.2 and `single_instance` came out in 4.3.
I suggest you to install the AUR package awesome-git or compile 4.3 direclty from awesome repo

**Comment by TheBeachMaster** [comment]
Thanks... Allow me to take a look and revert...

**Comment by TheBeachMaster** [comment]
Hello Papy.... You were right installing Awesome as detailed [here](https://github.com/awesomeWM/awesome#arch-linux-aur) worked...
