### ISSUE TITLE
networking icon

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#20]
system tray kind of thing on bottom has wifi icon. now i am connected to wire and dont want to use wifi but i am connected to it. on i3gaps i was able to click it and it shows all the wired and wireless connection which i can switch to. missing this badly in awesome.

**Comment by PapyElGringo** [comment]
Yeah I need to work on this
https://github.com/PapyElGringo/material-awesome/issues/9#issuecomment-461490841

In the mean time you can use the system tray like for the bluetooth with auto start "nm-applet"

**Comment by najamsk** [comment]
inside modules folder i modified autostart.lua and modify like following. check nm-applet its correct right.

```
run_once({'blueberry-tray'}) -- Bluetooth tray icon
run_once({'xfce4-power-manager'}) -- Power manager
run_once({'nm-applet'})
```

**Comment by PapyElGringo** [comment]
Yep then you should have it installed :)

**Comment by najamsk** [comment]
so i close it ? since you already have plans for it?

**Comment by najamsk** [comment]
since i am running nm-applet on autostart how can i remove wifi icon or widget from bottom area? i need to do that to free up some vertical space.

**Comment by najamsk** [comment]
i have removed the icon.
