### ISSUE TITLE
print screen

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#21]
i cant figure out printscreen. when i hit the print screen button on laptop its flicks but there is nothing saved in pictures folder or prompt for where to save.

**Comment by PapyElGringo** [comment]
When you press print screen you get a cursor you can drag to select an area or click on a window then it's go in the clip board then you can paste where you want

**Comment by najamsk** [comment]
nope not getting any cursor. print screen somehow is not working at all.

**Comment by najamsk** [comment]
just installed this program from "maim" available in manjaro packages and then print button from laptop started working. closing it.
