### ISSUE TITLE
ranger image previews

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#22]
ranger was installed with i3gaps on same laptop i have installed awesome and your configuration.  somehow ranger now not showing image files previews clearly instead showing some wired ascii kind of preview. i wanted to take screenshot but couldnt figure out how. so open filed separate issue for that.

**Comment by PapyElGringo** [comment]
Sorry I don't know what is it

**Comment by najamsk** [comment]
this is weird. its terminal specific issue few terminals like urxvt showing image previews in ranger properly. while my main terminal program terminator just messed up in awesome while working great in i3gaps.

**Comment by PapyElGringo** [comment]
Maybe open an issue direclty to awesomewm issue? https://github.com/awesomeWM/awesome

**Comment by najamsk** [comment]
i will open same issue on ranger and awesome. whoever resolve it first

**Comment by PapyElGringo** [comment]
Can I close this here? Don't know what to do about it

**Comment by najamsk** [comment]
yeh sure :) i just kept it open so if anyone else is trying awesome and your config. they know there is issue that needs to be solved either at ranger, awesome or terminal level.

**Comment by PapyElGringo** [comment]
Can you reference the related issues?

**Comment by najamsk** [comment]
if by that you mean from where i get this info. other issues on github or stackoverflow then will post links.

**Comment by PapyElGringo** [comment]
I mean you said you opened 2 issues on awesome and ranger so either you linked them to this issue otherwise we gonna close this because it's not related to this configuration ^^

**Comment by najamsk** [comment]
on i didnt open any issue anywhere else. lets close this from there.
