### ISSUE TITLE
Icons on the left aren't appearing

### ISSUE THREAD

**Issue by hubbcaps** [PapyElGringo/material-awesome#24]
Additionally, the time font looks to be a bit too fat.

Running on Arch Linux with all the optional prereqs installed.

Let me know if there is any more detail I can add, mostly just looking for some help troubleshooting whats going on here.

![image](https://user-images.githubusercontent.com/17379660/52819444-8785c880-3066-11e9-9a8e-de6aebe012a5.png)

**Comment by hubbcaps** [comment]
Also, I've switched my interface to the correct name in the wifi folder under widgets but it's not updating to show as connected even though I am. I see it's awking data out of /proc/net/wireless, looking under there on my system as my own user I only see the headers, but if I do it as root it shows all the info about my link.

Any way to work around this as well?

**Comment by hubbcaps** [comment]
Guess I should also mention, I'm running Arch on a Macbook Pro, retina 2880x1800 screen, perhaps resolution is the reason for the icon issues? Not sure where to start.

**Comment by PapyElGringo** [comment]
Yeah it's probably the resolution ! Nice let's fix this together it's should be simple enough.

I need to switch any integer value for a dpi(value) to auto resize the pixels

**Comment by hubbcaps** [comment]
That definitely sounds like it help, less dependancy on fixed sizes and would help to make it more response I guess would be the correct term. I'll wait for an attributed commit to get tagged to this issue and I'll test it out.

**Comment by PapyElGringo** [comment]
Try the last commit on master! How could I tag the commit?

**Comment by hubbcaps** [comment]
You can reference issue numbers in your commit message and it will show up in the issue itself for you:

https://stackoverflow.com/questions/1687262/link-to-the-issue-number-on-github-within-a-commit-message

I'll give your commit a go and see how it handles. Be back in a few with a report.

**Comment by PapyElGringo** [comment]
Ok I pushed 2 commits :)

**Comment by hubbcaps** [comment]
It works, the symbols are showing up now, but everything has become comically large lol

I should be able to get it changed to taste now that I have your changes as a reference though.

![image](https://user-images.githubusercontent.com/17379660/52823241-6f677680-3071-11e9-9a97-e5fd9f3970ab.png)

**Comment by hubbcaps** [comment]
Also, I got the wireless portion working by adding a sudo command to the awk against /proc/net/wireless

Obviously, this only works if you're set for sudo nopass, but it's one work around I figured out and it fits for me.

**Comment by PapyElGringo** [comment]
It's seem that the font size was already scaled I rollbacked it. For the wifi it's strange that the sudo is required..

**Comment by hubbcaps** [comment]
Yeah it's a bit odd, I think it has to do with the kernel being compiled with grsec vs a kernel that isn't.

You can see comparisions of my output here:

```
pandora :: .config/awesome » cat /proc/net/wireless 
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
pandora :: .config/awesome » sudo cat /proc/net/wireless 
Inter-| sta-|   Quality        |   Discarded packets               | Missed | WE
 face | tus | link level noise |  nwid  crypt   frag  retry   misc | beacon | 22
wlp3s0: 0000   70.  -27.  -256        0      0      0      0      0        0
```

**Comment by PapyElGringo** [comment]
Maybe we should try another command to get the same infos. I'll check tomorrow it's a bit late in Europe atm!

**Comment by hubbcaps** [comment]
Yeah man, take your time. My main concern was the icons and you fixed that promptly, everything else is just cherry on top. Appreciate your help, have a good night and thanks for the cool base configs!

**Comment by PapyElGringo** [comment]
Is `iwconfig`  available without sudo on your distrib?

**Comment by PapyElGringo** [comment]
What doest `echo /sys/class/net/*/wireless | awk -F'/' '{ print $5 }'` return in your system?

**Comment by PapyElGringo** [comment]
I will need some update on this or I will close the issue :disappointed:
