### ISSUE TITLE
No Panels after quiting fullscreen apps

### ISSUE THREAD

**Issue by BoredAbhi** [PapyElGringo/material-awesome#25]
If I go full-screen in an app (with Windows key+F) and quit the app (with Windows key + Q), then I am left with no panels. Both top and left panels fail to reappear after quitting.

**Comment by PapyElGringo** [comment]
Should be okay now :) thanks for reporting !

**Comment by BoredAbhi** [comment]
Wow ... didn't expect this fast fix. Issue resolved now.👍
