### ISSUE TITLE
Config not working as expected 

### ISSUE THREAD

**Issue by itzMaffi** [PapyElGringo/material-awesome#26]
### System

- MacOS 10.14.3
- Parallels Desktop 14.1.0 
- Debian 9.7 Stretch (2 Virtual Cores, 8GB RAM, 512MB VRAM)

### Packages

- Awesome 4.3 (Lua 5.3)
- Rofi 1.3.1
- Compton 0.1_beta2

### Issues

-  Awesome is not launching is fullscreen but in 4:3 aspect ratio, and ignores the window scaling settings. The cursor though is very small so the resolution of the screen is detected. My Gnome DE is fine.
- At time it becomes very slow or even unresponsive, without having any excessive CPU usage.
- Materia Theme and Papirus Icons are not loading even though they are the one set in the Tweak Tool.
- I can't lock the machine, just log out. Clicking on the lock just flashes the screen for a split second.
- The app search function in the sidebar doesn't work, and the standard Rofi prompt pops up instead. EDIT: Rofi doens't pop up anymore, the sidebar simply closes when clicking on the search textfield.

EDIT:
- Transparency and animations are missing.

**Comment by PapyElGringo** [comment]
1- In my opinion it's could be related to your Xorg configs
2- No clue yet
3- Tweak tool is only for gnome try with lxappearance
4- To lock your screen you need xlock-fancy-rapid
5- Strange...

**Comment by PapyElGringo** [comment]
The compton version is also strange ^^

**Comment by najamsk** [comment]
did he said mac? instead of linux. if awesome window manager is running on mac thats new for me. so cool :)
i do know mac os use unix kinda stuff under the hood.

**Comment by itzMaffi** [comment]
@najamsk Yes I said Mac, but that's just the host machine. I'm running Debian in VM. No widow manager for Mac. 

@PapyElGringo
1. I will check into Xorg conf, but I though those were shared, meaning that if my Gnome DE works, Awesome should work as well
2. Ok
3. Good to know
4. Good to know as well :)
5. Actually now Rofi shows up, but with its standard prompt
6. Related to compton and the transparency and animation, to check its version I just run a compton -v and checked the output after installing it from the fork.

**Comment by itzMaffi** [comment]
I can't find any package called xlock-fancy-rapid.

**Comment by PapyElGringo** [comment]
i3lock-fancy-rapid sorry https://github.com/yvbbrjdr/i3lock-fancy-rapid

**Comment by PapyElGringo** [comment]
Any updates on this?

**Comment by xolan** [comment]
Maybe this configuration path has something to do with it?

https://github.com/PapyElGringo/material-awesome/blob/master/configuration/apps.lua#L14
