### ISSUE TITLE
module/auto-start.lua: bad argument #1 to ipairs (table expected, got strings)

### ISSUE THREAD

**Issue by Alechan** [PapyElGringo/material-awesome#29]
The error is raised at startup.

the function "run_once" expects a table but in lines 17 and 19 it's given a string.

When replacing
run_once('compton --config ' .. filesystem.get_configuration_dir() .. '/conf/compton.conf')
-- To allow gnome tools to ask authentication like pamac
run_once(
  '/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)'
)

With
run_once(**{**'compton --config ' .. filesystem.get_configuration_dir() .. '/conf/compton.conf'**}**)
-- To allow gnome tools to ask authentication like pamac
run_once(**{**
  '/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg)'**}**
)

The error disappears.

**Comment by PapyElGringo** [comment]
Indeed thanks for the report I made a mistake with rollbacking a change :( will be fixed in rearange_project branch

**Comment by Alechan** [comment]
No problem. I saw your reddit post and wanted to try it out.

I've still to make it work but it looks promising.

Let me know if you need any more info on the other issues. I'd like to contribute as much as possible.
