### ISSUE TITLE
module "theme" not found at line 7

### ISSUE THREAD

**Issue by georges-hatem** [PapyElGringo/material-awesome#3]
i may be missing something, but i cloned the repo in ~/.config/awesome/material-awesome/...

From ~/.config/awesome/rc.lua, it loads ~/.config/awesome/material-awesome/rc.lua, but facing "module 'theme' not found at line 7.  
Any ideas?

**Comment by PapyElGringo** [comment]
hum the folder hierarchy are incorrect the folder material-awesome shouldn't exist and it's content should replace the awesome folder.
Did you used the command of the read me?
