### ISSUE TITLE
Missing unspecified dependencies when starting up (blueberry-tray, xfce4-power-manager, polkit)

### ISSUE THREAD

**Issue by Alechan** [PapyElGringo/material-awesome#31]
I get the following non-fatal errors when starting up awesome:
```
zsh:1: command not found: blueberry-tray
zsh:1: command not found: xfce4-power-manager
zsh:1: no such file or directory: /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
```

All of them are run in auto-start.lua

**Comment by PapyElGringo** [comment]
Yeah, I don't really know what to do about this. Theses a software I personally use but the config don't really depend on them. They could be replaced by any other or even removed.
What should I do about them?

**Comment by Alechan** [comment]
If it doesn't break anything, I recommend to just ignore it.

It could be refactored into a config file depending on their responsibilities so the user can change them with their prefered alternatives, but at this stage I think that that would just be overkill.
