### ISSUE TITLE
visual studio code full screen

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#33]
basically i was using visual studio code. and some how it was showing buttons for maximize, minimize and close. i clicked on maximize or full screen and from that point its not honoring layouts of any sort. tried everything. any idea?

**Comment by PapyElGringo** [comment]
Some apps use client side decorating title bar so they render themselves the buttons like google chrome or visual studio code. In both you can disable that to remove the titlebar.
In visual studio code for exemple there is an option called **Window: Title Bar Style** you can set it to **native**

Is there a little plane next to the app now?

Closing it and reopening it don't make it back to default?

**Comment by najamsk** [comment]
nope closing didn't work. so what i did lougout and log back in. that solves the problem of honoring tiled layout.

**Comment by PapyElGringo** [comment]
I added some code to prevent that coming so often. Tell me if it's help

**Comment by najamsk** [comment]
where is that code?
