### ISSUE TITLE
sending different programs to next screen/external display

### ISSUE THREAD

**Issue by najamsk** [PapyElGringo/material-awesome#34]
i connect one external display to my laptop. i want to send focus client (lets say vs code on tag3) to next screen. 

googling revealed mod4+ctrl+o or mod4+o to do it. but in config didnt find anything.

**Comment by najamsk** [comment]
i like to send clients/programs back and forth between both monitors under specific tags.

**Comment by PapyElGringo** [comment]
You can either add some custom shortcut into the global keys or you know you can press CMD aka WINDOW key and then drag and drop any client between screen

**Comment by najamsk** [comment]
i tried reading docs there was one binding mod4+o i added that to globalay.key inside conf folder but it was throwing error. i really need one key to move client to secondary screen. kinda stuck.

**Comment by PapyElGringo** [comment]
If you look the default config  here https://github.com/awesomeWM/awesome/blob/master/awesomerc.lua there is ``awful.key({ modkey,           }, "o",      function (c) c:move_to_screen()               end,
              {description = "move to screen", group = "client"})`` try to add this to the global

**Comment by najamsk** [comment]
i did and it was throwing all sort of errors. 

attempt to index a nil value (local 'c')

**Comment by PapyElGringo** [comment]
Sorry my bad add the code to https://github.com/PapyElGringo/material-awesome/blob/master/configuration/client/keys.lua instead

**Comment by najamsk** [comment]
you are amazing. you know that? solved.
