### ISSUE TITLE
Fullscreen program is hidden

### ISSUE THREAD

**Issue by Tragyn** [PapyElGringo/material-awesome#36]
Hi,

First off, I love this setup you've created.  It's beautiful!

My only problem is some programs launch hidden.  Kodi, for example.  If I run it, I hear the sounds it makes when it launches, I see it as a running process, but I can't find the window anywhere.  I looked through the config files for a window rule that might cause this but I found nothing.  This issue doesn't exist on other WMs, such as bspwm, for example.

Extra info: 
Fresh Arch install
Multi-monitor set up
AMDGPU Driver

Problem also exists on another computer, single monitor laptop, intel drivers.  I see this error when I try to launch Kodi:

> Oops, an error happened
/home/redmask/.config/awesome/layout/init.lua:44: attempt to index a nil value (field first_tag)

EDIT: Looks like it's not limited to fullscreen apps. I also can't see Steam. 
EDIT2: Kodi and Steam work fine with the stock awesomewm config.

**Comment by Tragyn** [comment]
Looks like it's not limited to fullscreen apps.  I also can't see Steam.

**Comment by Tragyn** [comment]
I installed i3-gaps and polybar and now Kodi and steam are both working...I assume some kind of wizardy happened or I just got lucky and one of those packages had a dep I was missing.

**Comment by Tragyn** [comment]
I rebooted and now Kodi and Steam are both broken again.

But I noticed something this time. When I reload awesome config, I can see the apps for a second before AwesomeWM returns. So they're there...they're just...stuck behind the WM? I'm not sure how that could happen.

**Comment by PapyElGringo** [comment]
Hello Tragyn, I don't think that your issue is related to this configuration but probably to AwesomeWM Itself.

Did you try to open them with the default AwesomeWM configuration to confirm that?

**Comment by Tragyn** [comment]
Yes it works fine with stock Awesome configuration.

**Comment by PapyElGringo** [comment]
Okaaaaay, I finally found the problem ! I don't know why but Kodi spawn without PID and so was used by the quake terminal module. Anyway it's should be fixed now !

Tell me if it's not the case.
