### ISSUE TITLE
Old filename still in use

### ISSUE THREAD

**Issue by Lord-Guckavin** [PapyElGringo/material-awesome#37]
I am really enjoying your theme but I have been having a little trouble setting it up but in my tinkering I found a that ./config/app.lua has a wrong line

`    'compton --config ' .. filesystem.get_configuration_dir() .. '/conf/compton.conf',`

/conf/compton.conf should be /configuration/compton.conf 

I am new to using github so if this is the wrong way to show issues please tell me

**Comment by PapyElGringo** [comment]
Thanks for your feedback ! I don't know why but I had this file updated in my local changes but I have never pushed it...

Thanks for telling me. It's should be fine now.

If you have other issues don't hesitate to open another.
