### ISSUE TITLE
Config errors on mirror of multiple displays

### ISSUE THREAD

**Issue by aebrer** [PapyElGringo/material-awesome#4]
I'm on the awesome-4.2 branch.

I set my secondary display to mirror my primary using xrandr:

    xrandr --output HDMI-1 --mode 1920x1080 --same-as eDP-1

This works great but causes some error popups, seen here in the attached screenshot.

![screenshot from 2019-02-07 09-48-01](https://user-images.githubusercontent.com/16313135/52419529-4ae22c00-2abe-11e9-8d3f-dbfac321c7d1.png)

**Comment by PapyElGringo** [comment]
Does it happen only once? When you switch from not mirroring to mirroring?
Does they appear when you restart awesome ctrl + cmd + r?

**Comment by aebrer** [comment]
Only once when I switch. They do not happen when I restart awesome.

**Comment by PapyElGringo** [comment]
this should be fixed in the last commit

**Comment by aebrer** [comment]
Fixed!
