### ISSUE TITLE
Cannot exit when using a single display

### ISSUE THREAD

**Issue by aebrer** [PapyElGringo/material-awesome#5]
On the 4.2 branch. Trying to exit does not work, and causes this error message:

![screenshot from 2019-02-07 10-10-12](https://user-images.githubusercontent.com/16313135/52420772-b75e2a80-2ac0-11e9-9b6a-8a429f16305b.png)

I have my primary display mirrored to my secondary.

**Comment by PapyElGringo** [comment]
You are trying to use the keyboard shortcuts ?

**Comment by aebrer** [comment]
Nope, using the button in the side panel. Nothing happens, but when I don't mirror, I do get the overlay appearing correctly on my secondary display only.

edit: I don't know the keyboard shortcuts.

**Comment by PapyElGringo** [comment]
Can you try last commit?

**Comment by aebrer** [comment]
Resolved!
