### ISSUE TITLE
Dolphin colors not changing

### ISSUE THREAD

**Issue by tausgus** [PapyElGringo/material-awesome#53]
I use Arch Linux, and followed this tutorial for installation.
When i set my colors using `lxappearance`, everything except the Dolphin colors changed. 
I also have Kvantum Engine installed and Materia set as my global theme for KDE Plasma, if that helps.

I'm new to this whole thing, so help would be nice.

![image](https://user-images.githubusercontent.com/55359861/79641031-b1240d80-819d-11ea-8929-532e08d55b5e.png)

**Comment by MadMagnetic** [comment]
Using Manjaro 20.0.3 with KDE and Awesome as second DE, Dolphin appears in white.
