### ISSUE TITLE
issues with compton

### ISSUE THREAD

**Issue by aebrer** [PapyElGringo/material-awesome#6]
On the 4.2 branch. Built and installed compton from the link in the readme. When it is running, blur effects don't show, and I get the following messages:

    [    60.93 ] error    9 BadDrawable  request  139 minor    4 serial  68069: "BadDrawable (invalid Pixmap or Window parameter)"
    [    60.94 ] error  143 BadPicture   request  139 minor    8 serial  68070: "RenderBadPicture (invalid Picture parameter)"
    [    60.94 ] error  143 BadPicture   request  139 minor    7 serial  68103: "RenderBadPicture (invalid Picture parameter)"
    [    60.94 ] error    4 BadPixmap    request   54 minor    0 serial  68104: "BadPixmap (invalid Pixmap parameter)"

**Comment by PapyElGringo** [comment]
How do you run it? It's should auto-run with awesome

**Comment by aebrer** [comment]
This was me running it manually from the terminal to see if I could diagnose why there are no blur effects.

**Comment by PapyElGringo** [comment]
If you want to run it from the terminal you need to run it with the path to the configuration file

But compton can run only one so before starting compton be sure no other compton is running with `killall compton` then `compton --config ~/.config/awesome/conf/compton.conf`

**Comment by aebrer** [comment]
Okay can confirm that blur and everything works when pointing to that config. However, now I have learned that compton is not starting on login.

**Comment by PapyElGringo** [comment]
Ok this was related to my awesomewm 4.2 rollback compatibility it's should work now on the 4.2 branch

**Comment by aebrer** [comment]
Confirmed fixed
