### ISSUE TITLE
Feature Request: Automatic Detection of Closed Laptop

### ISSUE THREAD

**Issue by aebrer** [PapyElGringo/material-awesome#7]
It would be nice if having the laptop lid closed would automatically mirror displays, or switch primary displays. Currently, I open my laptop, do this manually on login, then close my laptop again.

Just a small QOL thing.

**Comment by PapyElGringo** [comment]
This is related to Xorg configuration and not on material-awesome. My config is not supposed to configure all your computer behavior only the windows management. But Im not sure how to do this so with Xorg :D

**Comment by aebrer** [comment]
Okay I will look into this! Feel free to close the issue :)
