### ISSUE TITLE
themes not loading

### ISSUE THREAD

**Issue by aebrer** [PapyElGringo/material-awesome#8]
On 4.2 branch, the materia theme is installed and works on gnome, but doesn't show up properly in this WM. Screenshot attached:

![screenshot from 2019-02-07 10-50-48](https://user-images.githubusercontent.com/16313135/52423588-6b15e900-2ac6-11e9-9618-42e832b79e74.png)

**Comment by PapyElGringo** [comment]
This is not related to the configuration you need to activate the theme for GTK apps to do so you can use "lxappearance" that is a software to manage theme for gtk

**Comment by aebrer** [comment]
got it, now working thank you!
