### ISSUE TITLE
Widgets not working

### ISSUE THREAD

**Issue by aebrer** [PapyElGringo/material-awesome#9]
On the 4.2 branch:

The bluetooth widget does not appear, and the other two (battery and wifi) are only partially working. They show accurate information, and the hovertext works, but clicking on them does nothing.

**Comment by aebrer** [comment]
Volume widget does work, brightness does not.

**Comment by PapyElGringo** [comment]
The bluetooth is not really an widget but an tray icon you could use any you want but my config is setup to auto-start "blueberry-tray"

The battery widget display current charge and when you click on it start any software that manage the power in my case I use xfce4-power-manager but maybe you could make it to use the gnome default one but im not sure

The wifi widget is the same as the battery one it's display current connection status and when you click on it you can start any software that manage the wifi and for now.. I don't have any... I use wifi-menu from shell at the moment. I've planned to make an integrated solution but didn't had time to make it yet

**Comment by aebrer** [comment]
Okay good to know. Great work on this, the setup is pretty awesome!

**Comment by PapyElGringo** [comment]
Don't hesitate to ask for improvements I'll see what I can do

**Comment by PapyElGringo** [comment]
And for the luminosity it's required acpilight to be installed

**Comment by PapyElGringo** [comment]
Can I close this?

**Comment by aebrer** [comment]
Of course! I would recommend adding those dependencies to the README maybe, but I feel like the issue is more or less solved.
